theme = "my_flexoki_dark"

[editor]
line-number = "relative"
continue-comments = false
completion-timeout = 5
completion-trigger-len = 1
shell = ["powershell", "-C"]
true-color = true
color-modes = true
popup-border = "all"
end-of-line-diagnostics = "hint"
auto-pairs = false

[editor.statusline]
left = ["mode", "spacer", "version-control", "workspace-diagnostics"]
center = ["spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["primary-selection-length", "position", "position-percentage", "spacer"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.auto-save]
after-delay.enable = true

[editor.whitespace.render]
newline = "all"

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
C-u = [ "page_cursor_half_up", "align_view_center" ]
C-d = [ "page_cursor_half_down", "align_view_center" ]

[keys.insert]
j = { k = "normal_mode" }

