vim.g.mapleader = " "
vim.g.netrw_banner = 0
vim.g.netrw_liststyle = 3
vim.g.netrw_alto = 0
vim.g.netrw_preview = 1

vim.opt.clipboard = "unnamedplus"  -- use the clipboard as the unnamed register
vim.opt.cmdheight = 0              -- number of lines to use for the command-line
vim.opt.cmdwinheight = 5           -- Number of screen lines to use for the command-line window
vim.opt.completeopt = "fuzzy,menuone,noselect"
vim.opt.concealcursor = "nc"       -- Sets the modes in which text in the cursor line can also be concealed
-- vim.opt.conceallevel = 0           -- whether concealable text is shown or hidden
vim.opt.confirm = false             -- ask what to do about unsaved/read-only files
vim.opt.expandtab = true           -- use spaces when <Tab> is inserted
vim.opt.hlsearch = false           -- highlight matches with last search pattern
vim.opt.ignorecase = true          -- ignore case in search patterns
vim.opt.number = true              -- print the line number in front of each line
vim.opt.pumborder = "single"       -- Defines the default border style of popupmenu windows
vim.opt.pumheight = 15             -- maximum number of items to show in the popup menu
vim.opt.shiftround = true          -- round indent to multiple of shiftwidth
vim.opt.shiftwidth = 4             -- number of spaces to use for (auto)indent step
vim.opt.shortmess = "aoOstTWIcCFS" -- list of flags, reduce length of messages
vim.opt.showcmd = false            -- show (partial) command somewhere
vim.opt.showcmdloc = "statusline"  -- where to show (partial) command
vim.opt.signcolumn = "yes:1"         -- when and how to display the sign column
vim.opt.smartcase = true           -- no ignore case when pattern has uppercase
vim.opt.smartindent = true         -- smart autoindenting for C programs
vim.opt.smarttab = true            -- <Tab> in leading whitespace indents by 'shiftwidth'
vim.opt.softtabstop = 1           -- number of columns between two soft tab stops
vim.opt.splitbelow = true          -- new window from split is below the current one
vim.opt.splitright = true          -- new window is put right of the current one
vim.opt.statuscolumn = " %s%l%C  "        -- custom format for the status column
-- vim.opt.statusline = "" -- custom format for the status line
vim.opt.swapfile = false                  -- whether to use a swapfile for a buffer
vim.opt.tabstop = 4                       -- number of columns between two tab stops
vim.opt.termguicolors = true              -- enable 24-bit RGB color in the TUI
vim.opt.undofile = true                   -- save undo information in a file
vim.opt.wildmode = "noselect" -- Completion mode used for the character specified with 'wildchar'
vim.opt.wildoptions = "fuzzy,pum,tagfile" -- specifies how command line completion is done
vim.opt.winborder = "single"              -- defines the default border style of floating windows
vim.opt.wrap = false                      -- long lines wrap and continue on the next line
