unbind C-b
set-option -g prefix C-g
bind-key C-g send-prefix

set -g base-index 1
set -g pane-base-index 1

set -g default-terminal "xterm-256color"
set -a terminal-features "xterm-256color:RGB"
set -g history-limit 50000
set -g display-time 4000
set -g status-interval 5
set -g mouse on
set -sg escape-time 0
set -g set-clipboard external
setw -g aggressive-resize on

setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

set -g allow-passthrough on
# set -ga update-environment TERM
# set -ga update-environment TERM_PROGRAM

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind c new-window -c "#{pane_current_path}"

bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

bind r source-file "~/.config/tmux/tmux.conf"

set -g status on
set -g status-position top
set -g status-justify absolute-centre
set -g status-left "#{?client_prefix,#[fg=#ffcfa8]#[bg=#101010],#[fg=#ffffff]#[bg=#101010]}#{session_name}"
set -g status-right "#[fg=#ffffff,bg=#101010]%H:%M:%S"
set -g status-interval 1

set -g status-bg "#101010"
set -g window-status-activity-style "fg=#ffffff,bg=#101010,none"
set -g window-status-separator " "
set -g window-status-style "fg=#ffffff,bg=#101010,none"
set -g window-status-format "#{window_index}:#{window_name}"
set -g window-status-current-format "#[fg=#82d9c2,bg=#101010]#{window_index}:#{pane_current_command}"
